AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceIdentifier:
    Description: Identifies this instance of the application
    Type: String
  DynamoDBCapacityUnits:
    Description: The number of read and write capacity units for the DynamoDB table and indices.
    Type: Number
    MinValue: 1
    MaxValue: 20
Resources:
  HighScoreTable:
    Type: "AWS::DynamoDB::Table"
    Properties: 
      ProvisionedThroughput: 
        ReadCapacityUnits: !Ref DynamoDBCapacityUnits
        WriteCapacityUnits: !Ref DynamoDBCapacityUnits
      TableName: !Join [ "__", [ "Typoterminator-HighScore-Table", !Ref InstanceIdentifier] ]
      AttributeDefinitions: 
        - 
          AttributeName: "entityType"
          AttributeType: "S"
        - 
          AttributeName: "entityId"
          AttributeType: "S"
        - 
          AttributeName: "gameHistoryHashsum"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "entityType"
          KeyType: "HASH"
        - 
          AttributeName: "entityId"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "gameHistoryHashsumIndex"
          KeySchema:
          - 
            AttributeName: "entityType"
            KeyType: "HASH"
          - 
            AttributeName: "gameHistoryHashsum"
            KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref DynamoDBCapacityUnits
            WriteCapacityUnits: !Ref DynamoDBCapacityUnits
  TypoTerminatorUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: !Join [ "__", [ "Typoterminator-User", !Ref InstanceIdentifier] ]
      Policies:
        - PolicyName: "HighScoreTableAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "dynamodb:PutItem"
                  - "dynamodb:GetItem"
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                Resource: 
                  - !GetAtt HighScoreTable.Arn
                  - !Sub "${HighScoreTable.Arn}/index/*"